name: 'Share GraphQL Schema'
description: 'Share GraphQL Schema'

inputs:
  schema-paths:
    description: '["./server-a.graphql", "./server-b.graphql"]'
    required: true

outputs:
  sdl:
    description: sdl

runs:
  using: 'node16'
  main: 'build/index.js'
