name: 'Share GraphQL Schema'
description: 'Share GraphQL Schema'

inputs:
  base-server-urls:
    description: '["https://server-a.example.com/graphql", "https://server-b.example.com/graphql"]'
    required: true
  schema-file-pathname:
    description: 'schema.graphql Pathname (ex: ./schema.graphql)'
    required: true

outputs:
  sdl:
    description: sdl

runs:
  using: 'node16'
  main: 'build/index.js'
